apiVersion: v1
kind: Service
metadata:
  name: journal-service
spec:
  selector:
    app: journal-app # must match deployment labels
  ports:
    - protocol: TCP
      port: 5000 
      targetPort: 5000 
      nodePort: 30081
  type: NodePort
